### ISSUE TITLE
Use Environment Variables to configure app

### ISSUE THREAD

**Issue by rblaine95** [cannium/Sree#5]
Is there a way that one can use environment variables to configure the application?

For example:
```sh
docker run -it --rm -p 5000:5000 \
  -e ENDPOINT=https://s3.example.com/ \
  -e REGION=us1 \
  -e ACCESSKEY=123456789 \
  -e SECRETKEY=123456789abc \
  cannium/Sree
```

Which will then automatically configure the respective values.

**Comment by cannium** [comment]
I'm afraid not. I guess your intention is to hide AK and SK from web browser users, but internally Sree uses Amazon javascript SDK, which requires those keys. I believe AWS could create AK/SK pairs for individuals in your organization, so maybe this is more of a key pair management issue.

**Comment by rblaine95** [comment]
My intention is to use a local object storage provider in K8s (for example: Rook Ceph Object Storage), store `AccessKey` and `SecretKey`  in a K8s secret, and then deploy this and set the values in the dashboard with the keys stored in the secret.

Something like this:
```yaml
env:
  name: ACCESSKEY
  valueFrom:
    secretKeyRef:
      name: s3-keys
      key: AccessKey
  name: SECRETKEY
  valueFrom:
    secretKeyRef:
      name: s3-keys
      key: SecretKey
```

I can see that the `accessKeyId` and `secretKeyId` variables are set in JS

```js
initConfig: function () {
  var endpoint = window.localStorage.getItem('endpoint') || 'http://s3.amazonaws.com',
      region = window.localStorage.getItem('region') || 'us-east-1',
      accessKeyId = window.localStorage.getItem('accessKeyId'),
      secretKeyId = window.localStorage.getItem('secretKeyId');
  if((!accessKeyId || !secretKeyId) &&
      window.location.pathname !== '/config.html') {
      this.alert2('Please configure your keys first');
      window.setTimeout(function() {
          window.location = '/config.html';
      }, 2000);
}
```
For example, would it be possible to do something like this to set the values using environment variables on the system?
```js
var endpoint = window.localStorage.getItem('endpoint') || process.env.ENDPOINT || 'http://s3.amazonaws.com',
    region = window.localStorage.getItem('region') || process.env.REGION || 'us-east-1',
    accessKeyId = window.localStorage.getItem('accessKeyId') || process.env.ACCESSKEYID,
    secretKeyId = window.localStorage.getItem('secretKeyId') || process.env.SECRETKEYID;
```

**Comment by cannium** [comment]
The easiest hack would be changing the code as you listed, like 
```
    accessKeyId = window.localStorage.getItem('accessKeyId') || process.env.ACCESSKEYID,
```
and run a script to replace `process.env.ACCESSKEYID` with your AK from env, then start the service.
